-- Academy numbered profiles, numbered Global posts, profiles, previews, and posting limits.
-- Run once in Supabase after:
--   1. supabase/academy_schema.sql
--   2. supabase/academy_guest_reactions_migration.sql
--
-- This migration preserves existing Academy posts. The existing NYX guest post is
-- retroactively assigned profile number 1 and public post number 1.

begin;

create table if not exists public.academy_public_profiles (
  profile_number bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  username text not null unique
    check (username ~ '^[a-z0-9_]{2,32}$'),
  display_name text not null
    check (char_length(btrim(display_name)) between 1 and 80),
  avatar_index smallint not null default 0
    check (avatar_index between 0 and 7),
  bio text not null default ''
    check (char_length(bio) <= 400),
  twitter_url text,
  instagram_url text,
  facebook_url text,
  snapchat_url text,
  email text,
  email_is_public boolean not null default false,
  anonymous_mode boolean not null default false,
  owner_visitor_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint academy_public_profiles_twitter_url_check
    check (twitter_url is null or twitter_url ~* '^https?://'),
  constraint academy_public_profiles_instagram_url_check
    check (instagram_url is null or instagram_url ~* '^https?://'),
  constraint academy_public_profiles_facebook_url_check
    check (facebook_url is null or facebook_url ~* '^https?://'),
  constraint academy_public_profiles_snapchat_url_check
    check (snapchat_url is null or snapchat_url ~* '^https?://'),
  constraint academy_public_profiles_email_check
    check (email is null or char_length(btrim(email)) between 3 and 320)
);

insert into public.academy_public_profiles (
  profile_number,
  username,
  display_name,
  avatar_index
)
values (1, 'nyx', 'NYX', 0)
on conflict (profile_number) do update
set
  username = excluded.username,
  display_name = excluded.display_name;

-- Carry forward any Auth-backed profiles that already exist.
insert into public.academy_public_profiles (
  auth_user_id,
  username,
  display_name,
  avatar_index
)
select
  old_profile.id,
  old_profile.username,
  old_profile.display_name,
  old_profile.avatar_index
from public.profiles as old_profile
where old_profile.username <> 'nyx'
on conflict do nothing;

select setval(
  pg_get_serial_sequence('public.academy_public_profiles', 'profile_number'),
  greatest((select coalesce(max(profile_number), 0) from public.academy_public_profiles), 1),
  true
);

drop trigger if exists academy_public_profiles_set_updated_at
  on public.academy_public_profiles;
create trigger academy_public_profiles_set_updated_at
before update on public.academy_public_profiles
for each row execute function public.set_updated_at();

create or replace function public.sync_academy_public_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.academy_public_profiles (
    auth_user_id,
    username,
    display_name,
    avatar_index
  )
  values (new.id, new.username, new.display_name, new.avatar_index)
  on conflict (auth_user_id) do update
  set
    username = excluded.username,
    display_name = excluded.display_name,
    avatar_index = excluded.avatar_index;

  return new;
end;
$$;

drop trigger if exists profiles_sync_academy_public_profile on public.profiles;
create trigger profiles_sync_academy_public_profile
after insert or update of username, display_name, avatar_index on public.profiles
for each row execute function public.sync_academy_public_profile();

alter table public.academy_comments
  add column if not exists profile_number bigint
    references public.academy_public_profiles(profile_number) on delete restrict,
  add column if not exists post_number bigint,
  add column if not exists is_anonymous boolean not null default false,
  add column if not exists browser_author_id uuid;

-- NYX's existing guest rows become posts by public profile number 1.
update public.academy_comments
set profile_number = 1
where profile_number is null
  and user_id is null
  and guest_name = 'NYX';

-- Map any existing authenticated rows to their public profile number.
update public.academy_comments as comment
set profile_number = public_profile.profile_number
from public.academy_public_profiles as public_profile
where comment.profile_number is null
  and comment.user_id = public_profile.auth_user_id;

do $$
begin
  if exists (
    select 1
    from public.academy_comments
    where profile_number is null
  ) then
    raise exception 'Every Academy post must map to an Academy public profile before this migration can finish';
  end if;
end;
$$;

alter table public.academy_comments
  alter column profile_number set not null;

create sequence if not exists public.academy_post_number_seq;

with numbered_posts as (
  select
    comment.id,
    row_number() over (order by comment.created_at, comment.id)
      + coalesce((select max(existing.post_number) from public.academy_comments as existing), 0)
      as assigned_number
  from public.academy_comments as comment
  where comment.post_number is null
)
update public.academy_comments as comment
set post_number = numbered_posts.assigned_number
from numbered_posts
where comment.id = numbered_posts.id;

select setval(
  'public.academy_post_number_seq'::regclass,
  greatest((select coalesce(max(post_number), 0) from public.academy_comments), 1),
  (select count(*) > 0 from public.academy_comments)
);

alter table public.academy_comments
  alter column post_number set default nextval('public.academy_post_number_seq'::regclass),
  alter column post_number set not null;

create unique index if not exists academy_comments_post_number_key
  on public.academy_comments (post_number);

create index if not exists academy_comments_profile_created_at_idx
  on public.academy_comments (profile_number, created_at desc)
  where deleted_at is null;

create or replace function public.academy_visible_character_count(p_body text)
returns integer
language sql
immutable
strict
set search_path = ''
as $$
  select char_length(
    btrim(
      regexp_replace(
        p_body,
        '(https?://|www\.)[^[:space:]]+',
        '',
        'gi'
      )
    )
  );
$$;

alter table public.academy_comments
  add column if not exists visible_character_count smallint
    generated always as (public.academy_visible_character_count(body)) stored;

alter table public.academy_comments
  drop constraint if exists academy_comments_body_check,
  drop constraint if exists academy_comments_visible_character_count_check;

alter table public.academy_comments
  add constraint academy_comments_body_check
    check (char_length(btrim(body)) between 1 and 5000),
  add constraint academy_comments_visible_character_count_check
    check (visible_character_count between 0 and 500);

create or replace function public.enforce_academy_global_post_cooldown()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.parent_id is null and exists (
    select 1
    from public.academy_comments as recent_post
    where recent_post.profile_number = new.profile_number
      and recent_post.parent_id is null
      and recent_post.deleted_at is null
      and recent_post.created_at > now() - interval '24 hours'
  ) then
    raise exception 'Global posting is limited to once every 24 hours';
  end if;

  return new;
end;
$$;

drop trigger if exists academy_global_post_cooldown on public.academy_comments;
create trigger academy_global_post_cooldown
before insert on public.academy_comments
for each row execute function public.enforce_academy_global_post_cooldown();

drop view if exists public.academy_comment_feed;
create view public.academy_comment_feed as
select
  comment.id,
  comment.post_number,
  comment.parent_id,
  case when comment.is_anonymous then null else comment.profile_number end as profile_number,
  case
    when comment.is_anonymous then 'ANON'
    else coalesce(public_profile.display_name, comment.guest_name, 'Academy Member')
  end as author_name,
  case when comment.is_anonymous then null else public_profile.avatar_index end as avatar_index,
  comment.body,
  comment.visible_character_count,
  comment.created_at,
  comment.likes_count,
  comment.dislikes_count,
  comment.is_anonymous
from public.academy_comments as comment
left join public.academy_public_profiles as public_profile
  on public_profile.profile_number = comment.profile_number
where comment.deleted_at is null;

drop view if exists public.academy_profile_directory;
create view public.academy_profile_directory as
select
  profile.profile_number,
  profile.username,
  profile.display_name,
  profile.avatar_index,
  profile.bio,
  profile.twitter_url,
  profile.instagram_url,
  profile.facebook_url,
  profile.snapchat_url,
  case when profile.email_is_public then profile.email else null end as email,
  profile.email_is_public,
  profile.created_at
from public.academy_public_profiles as profile;

create or replace function public.assert_nyx_academy_owner(p_visitor_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  stored_owner uuid;
begin
  if p_visitor_id is null then
    raise exception 'A browser visitor ID is required';
  end if;

  select profile.owner_visitor_id
  into stored_owner
  from public.academy_public_profiles as profile
  where profile.profile_number = 1
  for update;

  if not found then
    raise exception 'NYX profile number 1 does not exist';
  end if;

  if stored_owner is null then
    update public.academy_public_profiles
    set owner_visitor_id = p_visitor_id
    where profile_number = 1;
  elsif stored_owner <> p_visitor_id then
    raise exception 'This browser does not own the NYX profile';
  end if;
end;
$$;

create or replace function public.academy_nyx_post_status(p_visitor_id uuid)
returns table (
  can_post boolean,
  next_post_at timestamptz,
  anonymous_mode boolean,
  is_owner boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with profile_state as (
    select
      profile.owner_visitor_id,
      profile.anonymous_mode
    from public.academy_public_profiles as profile
    where profile.profile_number = 1
  ), latest_post as (
    select max(comment.created_at) as created_at
    from public.academy_comments as comment
    where comment.profile_number = 1
      and comment.parent_id is null
      and comment.deleted_at is null
  )
  select
    (profile_state.owner_visitor_id is null or profile_state.owner_visitor_id = p_visitor_id)
      and (latest_post.created_at is null or latest_post.created_at <= now() - interval '24 hours'),
    case
      when latest_post.created_at is null then null
      else latest_post.created_at + interval '24 hours'
    end,
    profile_state.anonymous_mode,
    profile_state.owner_visitor_id is null or profile_state.owner_visitor_id = p_visitor_id
  from profile_state
  cross join latest_post;
$$;

create or replace function public.create_nyx_academy_post(
  p_body text,
  p_visitor_id uuid
)
returns setof public.academy_comment_feed
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_comment_id bigint;
  post_anonymously boolean;
begin
  perform public.assert_nyx_academy_owner(p_visitor_id);

  select profile.anonymous_mode
  into post_anonymously
  from public.academy_public_profiles as profile
  where profile.profile_number = 1;

  insert into public.academy_comments (
    user_id,
    guest_name,
    profile_number,
    body,
    is_anonymous,
    browser_author_id
  )
  values (
    null,
    'NYX',
    1,
    btrim(p_body),
    post_anonymously,
    p_visitor_id
  )
  returning id into new_comment_id;

  return query
  select feed.*
  from public.academy_comment_feed as feed
  where feed.id = new_comment_id;
end;
$$;

create or replace function public.delete_nyx_academy_post(
  p_post_number bigint,
  p_visitor_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  perform public.assert_nyx_academy_owner(p_visitor_id);

  update public.academy_comments as comment
  set deleted_at = now()
  where comment.profile_number = 1
    and comment.post_number = p_post_number
    and comment.deleted_at is null
    and (comment.browser_author_id = p_visitor_id or comment.browser_author_id is null);

  get diagnostics deleted_count = row_count;
  return deleted_count = 1;
end;
$$;

create or replace function public.get_nyx_academy_profile(p_visitor_id uuid)
returns table (
  profile_number bigint,
  username text,
  display_name text,
  avatar_index smallint,
  bio text,
  twitter_url text,
  instagram_url text,
  facebook_url text,
  snapchat_url text,
  email text,
  email_is_public boolean,
  anonymous_mode boolean,
  is_owner boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    profile.profile_number,
    profile.username,
    profile.display_name,
    profile.avatar_index,
    profile.bio,
    profile.twitter_url,
    profile.instagram_url,
    profile.facebook_url,
    profile.snapchat_url,
    case
      when profile.owner_visitor_id is null or profile.owner_visitor_id = p_visitor_id
        then profile.email
      when profile.email_is_public then profile.email
      else null
    end,
    profile.email_is_public,
    profile.anonymous_mode,
    profile.owner_visitor_id is null or profile.owner_visitor_id = p_visitor_id
  from public.academy_public_profiles as profile
  where profile.profile_number = 1;
$$;

create or replace function public.update_nyx_academy_profile(
  p_visitor_id uuid,
  p_display_name text,
  p_avatar_index smallint,
  p_bio text,
  p_twitter_url text,
  p_instagram_url text,
  p_facebook_url text,
  p_snapchat_url text,
  p_email text,
  p_email_is_public boolean,
  p_anonymous_mode boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.assert_nyx_academy_owner(p_visitor_id);

  update public.academy_public_profiles
  set
    display_name = left(btrim(p_display_name), 80),
    avatar_index = p_avatar_index,
    bio = coalesce(p_bio, ''),
    twitter_url = nullif(btrim(p_twitter_url), ''),
    instagram_url = nullif(btrim(p_instagram_url), ''),
    facebook_url = nullif(btrim(p_facebook_url), ''),
    snapchat_url = nullif(btrim(p_snapchat_url), ''),
    email = nullif(btrim(p_email), ''),
    email_is_public = coalesce(p_email_is_public, false),
    anonymous_mode = coalesce(p_anonymous_mode, false)
  where profile_number = 1;
end;
$$;

alter table public.academy_public_profiles enable row level security;

-- The public-facing views deliberately exclude private browser ownership data.
revoke all on table public.academy_public_profiles from anon, authenticated;
revoke select, insert on table public.academy_comments from anon, authenticated;
revoke all on sequence public.academy_post_number_seq from anon, authenticated;

grant select on public.academy_comment_feed to anon, authenticated;
grant select on public.academy_profile_directory to anon, authenticated;

revoke all on function public.assert_nyx_academy_owner(uuid) from public;
revoke all on function public.academy_nyx_post_status(uuid) from public;
revoke all on function public.create_nyx_academy_post(text, uuid) from public;
revoke all on function public.delete_nyx_academy_post(bigint, uuid) from public;
revoke all on function public.get_nyx_academy_profile(uuid) from public;
revoke all on function public.update_nyx_academy_profile(
  uuid, text, smallint, text, text, text, text, text, text, boolean, boolean
) from public;

grant execute on function public.academy_nyx_post_status(uuid) to anon, authenticated;
grant execute on function public.create_nyx_academy_post(text, uuid) to anon, authenticated;
grant execute on function public.delete_nyx_academy_post(bigint, uuid) to anon, authenticated;
grant execute on function public.get_nyx_academy_profile(uuid) to anon, authenticated;
grant execute on function public.update_nyx_academy_profile(
  uuid, text, smallint, text, text, text, text, text, text, boolean, boolean
) to anon, authenticated;

commit;
