export const insectFeatures = ['DcbEVC1sry_', 'DceSjjPs3dt'].map((post, index) => ({
  id: String(index + 1),
  title: `Insect ${index + 1}`,
  url: `https://www.instagram.com/p/${post}/`,
  embedUrl: `https://www.instagram.com/p/${post}/embed/`,
}))

export const scienceFeatures = {
  animals: ['DbioI_Wum6R', 'DcjIGVXRH5l'].map((post, index) => ({
    id: String(index + 1),
    title: `Animals ${index + 1}`,
    url: `https://www.instagram.com/p/${post}/`,
    embedUrl: `https://www.instagram.com/p/${post}/embed/`,
  })),
  health: [
    {
      id: '01',
      title: 'Shoulder-blade stretch',
      handle: '@jamesmoorewellness',
      analysis: 'A physical-health demo for stretching the spot between your shoulder blades.',
      image: '/health-physical-shoulder-stretch.png',
      imageAlt: 'A seated demonstration of a stretch for the area between the shoulder blades',
      url: 'https://www.instagram.com/p/DWm5QRLkRLh/',
      embedUrl: 'https://www.instagram.com/p/DWm5QRLkRLh/embed/',
    },
    {
      id: '02',
      title: 'Hip-release exercise',
      handle: '@jamesmoorewellness',
      analysis: 'A mobility exercise for releasing tension through the hips and lower back.',
      image: '/health-physical-hip-release.png',
      imageAlt: 'A kneeling hip-mobility exercise demonstrated on a gym floor',
      url: 'https://www.instagram.com/p/DZFYq8PRuB4/',
      embedUrl: 'https://www.instagram.com/p/DZFYq8PRuB4/embed/',
    },
    {
      id: '03',
      title: 'Doorway mobility',
      handle: '@jamesmoorewellness',
      analysis: 'A gentle doorway mobility demonstration for the neck and upper shoulder.',
      image: '/health-physical-doorway-stretch.png',
      imageAlt: 'A man demonstrating a gentle stretch while holding a doorway',
      url: 'https://www.instagram.com/p/DZPzwfsxjlZ/',
      embedUrl: 'https://www.instagram.com/p/DZPzwfsxjlZ/embed/',
    },
    {
      id: '04',
      title: 'Walking mechanics',
      handle: '@conor_harris_',
      analysis: 'A practical drill focused on foot movement and walking mechanics.',
      image: '/health-physical-walking-mechanics.png',
      imageAlt: 'A barefoot walking-mechanics demonstration inside a gym',
      url: 'https://www.instagram.com/p/DY7gZemPj1r/',
      embedUrl: 'https://www.instagram.com/p/DY7gZemPj1r/embed/',
    },
    {
      id: '05',
      title: 'Muhammad Ali footwork',
      handle: '@nickballtraining',
      analysis: 'A breakdown of Muhammad Ali’s movement and athletic footwork.',
      image: '/health-physical-ali-footwork.png',
      imageAlt: 'Muhammad Ali moving inside a boxing ring',
      url: 'https://www.instagram.com/p/DWHn8UuEZxd/',
      embedUrl: 'https://www.instagram.com/p/DWHn8UuEZxd/embed/',
    },
    {
      id: '06',
      title: 'Health 06',
      handle: '@physicsuncovered',
      analysis: 'A new selection in the Health collection.',
      url: 'https://www.instagram.com/p/DZ29EbySiHr/',
      embedUrl: 'https://www.instagram.com/p/DZ29EbySiHr/embed/',
    },
    {
      id: '07',
      title: 'Health 07',
      handle: '@jamesmoorewellness',
      analysis: 'The seventh selection in the Health collection.',
      url: 'https://www.instagram.com/p/DaiZMffN0iJ/',
      embedUrl: 'https://www.instagram.com/p/DaiZMffN0iJ/embed/',
    },
    {
      id: '08',
      title: 'Health 08',
      handle: '@frederickhperry',
      analysis: 'The eighth selection in the Health collection.',
      url: 'https://www.instagram.com/p/DbbfDb-Rgdv/',
      embedUrl: 'https://www.instagram.com/p/DbbfDb-Rgdv/embed/',
    },
    {
      id: '09',
      title: 'Health 09',
      handle: '@robunedited',
      analysis: 'The ninth selection in the Health collection.',
      url: 'https://www.instagram.com/p/Dcg0s3qBW9R/',
      embedUrl: 'https://www.instagram.com/p/Dcg0s3qBW9R/embed/',
    },
    {
      id: '10',
      title: 'Health 10',
      handle: '@soulscienceconnect',
      analysis: 'The tenth selection in the Health collection.',
      url: 'https://www.instagram.com/p/Db_XlsggFcD/?img_index=1',
      embedUrl: 'https://www.instagram.com/p/Db_XlsggFcD/embed/',
    },
  ],
  physics: [
    {
      id: '01',
      title: 'Physics 01',
      handle: '@outtstanding',
      analysis: 'The first selection in the Physics collection.',
      url: 'https://www.instagram.com/p/DZBOEOQjF1v/',
      embedUrl: 'https://www.instagram.com/p/DZBOEOQjF1v/embed/',
    },
  ],
  looksmaxxing: [
    {
      id: '01',
      title: 'NYX',
      handle: '@nyx_vostok',
      analysis: "Me. Founder of the site. First facial athlete. There are looksmaxxers, there are facial yoga people but then there's me, who tries to focus on the whole compass of improving your face, across the board.",
      url: 'https://www.instagram.com/p/Dcd2UceA3Sy/',
      embedUrl: 'https://www.instagram.com/p/Dcd2UceA3Sy/embed/',
    },
    {
      id: '02',
      title: 'Looksmaxxing 02',
      handle: '@a95_ofc',
      analysis: 'The second selection in the Looksmaxxing collection.',
      url: 'https://www.instagram.com/p/DcXnGm0ueXh/',
      embedUrl: 'https://www.instagram.com/p/DcXnGm0ueXh/embed/',
    },
    {
      id: '03',
      title: 'Looksmaxxing 03',
      handle: '@justic3j',
      analysis: 'The third selection in the Looksmaxxing collection.',
      url: 'https://www.instagram.com/p/DaordoytyuR/',
      embedUrl: 'https://www.instagram.com/p/DaordoytyuR/embed/',
    },
    {
      id: '04',
      title: 'Looksmaxxing 04',
      handle: '@reidascendent',
      analysis: 'The fourth selection in the Looksmaxxing collection.',
      url: 'https://www.instagram.com/p/DbeUU8KRdJj/',
      embedUrl: 'https://www.instagram.com/p/DbeUU8KRdJj/embed/',
    },
    {
      id: '05',
      title: 'Looksmaxxing 05',
      handle: '@livelikelucass',
      analysis: 'The fifth selection in the Looksmaxxing collection.',
      url: 'https://www.instagram.com/p/DZ93eCetQKa/',
      embedUrl: 'https://www.instagram.com/p/DZ93eCetQKa/embed/',
    },
  ],
  workout: [
    {
      id: '01',
      title: 'Workout 01',
      handle: '@kiandeehanfitness',
      analysis: 'The first selection in the Workout collection.',
      url: 'https://www.instagram.com/p/DchGIrEyv3m/',
      embedUrl: 'https://www.instagram.com/p/DchGIrEyv3m/embed/',
    },
  ],
  astrology: [
    ...['Dcp2NqmlFEt', 'DctNz-AADQF', 'Dcq0_JOpjXJ', 'Db8pYpjgJur'].map((post, index) => ({
      id: String(index + 2).padStart(2, '0'),
      title: `Astrology ${index + 2}`,
      url: `https://www.instagram.com/p/${post}/`,
      embedUrl: `https://www.instagram.com/p/${post}/embed/`,
    })),
    {
      id: '01',
      title: 'Astrology 01',
      handle: '@galaxies',
      analysis: 'The first selection in the Astrology collection.',
      url: 'https://www.instagram.com/p/DcSBTB7kcNw/?img_index=1',
      embedUrl: 'https://www.instagram.com/p/DcSBTB7kcNw/embed/',
    },
  ],
}
