const localVideos = new Set(['DbMBzJ1JyTN', 'Dbyznf2xiMM', 'DbLdtygoqG3'])

function instagramPost(id, post, title, caption) {
  return { id, title, caption, url: `https://www.instagram.com/p/${post}/`, embedUrl: `https://www.instagram.com/p/${post}/embed/`, videoSrc: localVideos.has(post) ? `/instagram-videos/${post}.mp4` : undefined }
}

export const cultureSubcategories = {
  'video-games': {
    mainLabel: 'World of Warcraft',
    label: 'Elder Scrolls',
    features: [instagramPost('elder-scrolls-01', 'DVbNovYAoNY', 'Elder Scrolls')],
  },
  comedy: {
    mainLabel: 'Comedy',
    label: 'Trolling',
    features: [
      instagramPost('trolling-01', 'DcQ8ZH5RR0l', 'Trolling 01'),
      instagramPost('trolling-02', 'DcSXELpxRe-', 'Trolling 02'),
      instagramPost('trolling-03', 'DbWdFhYvGGH', 'Trolling 03'),
    ],
    additionalTabs: [
      { key: 'race', label: 'Race', features: [instagramPost('race-01', 'DbleqfbMqtr', 'Comedy — Race')] },
      { key: 'drugs', label: 'Drugs', features: [instagramPost('drugs-01', 'DbltmCzviKb', 'Comedy — Drugs')] },
    ],
  },
  art: {
    mainLabel: 'Modern Art',
    label: 'AI Art',
    features: [instagramPost('ai-art', 'Db03EO5CJi-', 'AI Art')],
    additionalTabs: [{ key: 'dance', label: 'Dance', features: [instagramPost('dance', 'DaGlreySLHG', 'Dance')] }],
  },
  street: {
    mainLabel: 'Street',
    label: 'Bike Culture',
    features: [
      instagramPost('bike-01', 'DctXtQIoDvd', 'Bike Culture 01'),
      instagramPost('bike-02', 'DblkvF_phb-', 'Bike Culture 02'),
      instagramPost('bike-03', 'Da_G7iyJZbW', 'Bike Culture 03'),
      instagramPost('bike-04', 'Db6Uz8VgmFH', 'Bike Culture 04'),
      instagramPost('bike-05', 'DWwKh0Uubi4', 'Bike Culture 05'),
      instagramPost('bike-06', 'DbBEss_OAf5', 'Bike Culture 06'),
      instagramPost('bike-07', 'DceoTa5SCg-', 'Bike Culture 07'),
      instagramPost('bike-08', 'Db6Vdg0RPEr', 'Bike Culture 08'),
      instagramPost('bike-09', 'Da6tp1nNE4L', 'Bike Culture 09'),
      instagramPost('bike-10', 'DcWdscNO7Fp', 'Bike Culture 10'),
      instagramPost('bike-11', 'DcaLAUXtFOx', 'Bike Culture 11'),
    ],
    additionalTabs: [
      { key: 'skateboarder', label: 'Skateboarder', features: [instagramPost('skateboarder-01', 'DaUQ8Erhdff', 'Skateboarder 01')] },
      { key: 'vagabond', label: 'Vagabond', features: [instagramPost('vagabond-01', 'DXnEqZiAZq1', 'Vagabond 01')] },
      { key: 'self-defense', label: 'Self Defense', features: [
        instagramPost('self-defense-01', 'DcgyffbJvCh', 'Self Defense 01'),
        instagramPost('self-defense-02', 'DZvOStui1jb', 'Self Defense 02'),
      ] },
      { key: 'race', label: 'Race', features: [instagramPost('race-01', 'Dcmfo4vvNQp', 'Street — Race')] },
      { key: 'prison', label: 'Prison', features: [instagramPost('prison-01', 'DWMoMkeAVLV', 'Street — Prison')] },
      { key: 'racing', label: 'Racing', features: [
        instagramPost('racing-01', 'Dbl7REKy_gS', 'Racing 01'),
        instagramPost('racing-02', 'DaYyRtgypOe', 'Racing 02'),
        instagramPost('racing-03', 'DcPwYjPibl-', 'Racing 03'),
        instagramPost('racing-04', 'DasTZg2zwsJ', 'Racing 04'),
        instagramPost('racing-05', 'Da5WdDzOSN1', 'Racing 05'),
      ] },
    ],
  },
  religion: {
    mainLabel: 'Religion',
    label: 'AI Interpretation',
    features: [
      instagramPost('ai-interpretation', 'DcPiHyXhInd', 'AI Interpretation'),
      instagramPost('ai-interpretation-02', 'DcmTM4mTz9j', 'AI Interpretation 02'),
    ],
    additionalTabs: [{ key: 'occult', label: 'Occult', features: [
      instagramPost('occult-01', 'Dclt6JHsf3m', 'Occult'),
      instagramPost('occult-02', 'DcTv6aeu0Jk', 'Occult 02'),
      instagramPost('occult-03', 'DYd7RJ8OYFv', 'Occult 03'),
    ] }],
  },
  history: {
    label: 'AI Recreation',
    features: [
      instagramPost('rome', 'Dbyznf2xiMM', 'AI recreation of Rome', 'what Rome looked like 2000 years ago'),
      instagramPost('prehistory', 'DbMBzJ1JyTN', 'AI recreation of prehistory', 'what 50,000 years ago may have looked like.'),
      instagramPost('ai-history-03', 'DbLdtygoqG3', 'AI Recreation 03'),
    ],
  },
  fights: {
    label: 'Tips',
    features: [
      instagramPost('tips', 'DZKYSqYSwnb', 'Fighting tips'),
      instagramPost('tips-02', 'DcRAMa4Tf5_', 'Fighting tips 02'),
      instagramPost('tips-03', 'DcnPWdLhlR4', 'Fighting tips 03'),
      instagramPost('tips-04', 'DZybyY7tZvv', 'Fighting tips 04'),
    ],
  },
  'new-age-athletes': {
    label: 'New Techniques',
    features: [instagramPost('techniques', 'DZ9yvVCuzQI', 'New techniques')],
  },
}

export const cultureFeatures = {
  contemplative: [instagramPost('01', 'DaimOeDuDfO', 'Contemplative 01')],
  film: [instagramPost('01', 'DcMZN9jMDyD', 'Film 01')],
  'video-games': [
    instagramPost('wow-01', 'Db5egH6Rr0n', 'World of Warcraft'),
    instagramPost('wow-02', 'Dcdz4p_TNSH', 'World of Warcraft 02'),
  ],
  foids: [
    instagramPost('03', 'Db1Vtq0yFuR', 'Foids 03'),
    instagramPost('04', 'DcaEg9ulmvI', 'Foids 04'),
    instagramPost('01', 'DcTvUm4KxmA', 'Foids 01'),
    instagramPost('02', 'DcFg_9nN8Ue', 'Foids 02'),
  ],
  street: [
    instagramPost('01', 'DcsznNTSi-4', 'Street 01'),
    instagramPost('02', 'DbeFq8Vy1rF', 'Street 02'),
  ],
  music: [
    {
      id: '01',
      title: 'pr0crastn8',
      handle: '@pr0crastn8',
      analysis: 'New artist, still figuring out his sound 6/10, intersting.',
      image: '/culture-music-pr0crastn8.png',
      imageAlt: 'A musician framed by an electric-blue circular mirror',
      url: 'https://www.instagram.com/p/DYL5FOKzq7Q/',
      embedUrl: 'https://www.instagram.com/p/DYL5FOKzq7Q/embed/',
    },
    {
      id: '02',
      title: 'iam24th',
      handle: '@iam24th',
      analysis: 'New music find: “yeah huh and i get it.”',
      image: '/culture-music-iam24th.png',
      imageAlt: 'A hooded musician standing beside the ocean',
      url: 'https://www.instagram.com/p/DWkLVRzx_sm/',
      embedUrl: 'https://www.instagram.com/p/DWkLVRzx_sm/embed/',
    },
    {
      id: '03',
      title: 'corpo.corpo.corpo',
      handle: '@corpo.corpo.corpo',
      analysis: 'A new atmospheric music selection.',
      image: '/culture-music-corpo.png',
      imageAlt: 'A pale, glitched music-video frame in a wooded landscape',
      url: 'https://www.instagram.com/p/DZWPUnTAN86/',
      embedUrl: 'https://www.instagram.com/p/DZWPUnTAN86/embed/',
      additionalLinks: [
        {
          label: 'Second music post',
          url: 'https://www.instagram.com/p/DYIetfiyx4f/',
        },
      ],
    },
  ],
  memes: [
    {
      id: '01',
      title: 'Me in the car',
      handle: '@unemployed.clipper',
      analysis: 'Mechanic: How did you not hear the noise your car was making?',
      image: '/culture-meme-mechanic.png',
      imageAlt: 'A man vibing in a car beneath a mechanic joke',
      url: 'https://www.instagram.com/p/DYkj1BHJkkr/',
      embedUrl: 'https://www.instagram.com/p/DYkj1BHJkkr/embed/',
    },
    {
      id: '02',
      title: 'Average Instagram user',
      handle: '@offbeatoffender',
      image: '/culture-meme-instagram-user.png',
      imageAlt: 'Average Instagram user meme over an illustrated photo album',
      url: 'https://www.instagram.com/p/DTNor-fkgxO/',
      embedUrl: 'https://www.instagram.com/p/DTNor-fkgxO/embed/',
    },
    {
      id: '03',
      title: 'My favorite word',
      handle: '@clips',
      analysis: 'Me at 80 years old with dementia trying to remember my favorite word.',
      image: '/culture-meme-favorite-word.png',
      imageAlt: 'A nighttime movie scene beneath a joke about remembering a favorite word',
      url: 'https://www.instagram.com/p/DT90Nv0Etb_/',
      embedUrl: 'https://www.instagram.com/p/DT90Nv0Etb_/embed/',
    },
  ],
  comedy: [
    instagramPost('10', 'DcZEWVAjRa-', 'Comedy 10'),
    instagramPost('11', 'DceM1pLNZkp', 'Comedy 11'),
    instagramPost('12', 'DcfNCvHu75L', 'Comedy 12'),
    instagramPost('13', 'DcMpJ71RS_r', 'Comedy 13'),
    instagramPost('14', 'DcWgfFwJOo7', 'Comedy 14'),
    instagramPost('15', 'Dbs9pJoRCHQ', 'Comedy 15'),
    instagramPost('16', 'DcPgrpfuWjd', 'Comedy 16'),
    instagramPost('09', 'DcQJjYIJoQg', 'Comedy 09'),
    instagramPost('07', 'DXKzXBwERBh', 'Comedy 07'),
    instagramPost('08', 'DcnnswKsXf2', 'Comedy 08'),
    instagramPost('06', 'DbRMDtFxmpo', 'Comedy 06'),
    instagramPost('05', 'Dct181wJb30', 'Comedy 05'),
    {
      id: '01',
      title: 'Railroad crossing',
      handle: '@slimerboy9000',
      analysis: 'A quick drive-by comedy clip.',
      image: '/culture-comedy-railroad.png',
      imageAlt: 'A driver waiting behind a car at a railroad crossing',
      url: 'https://www.instagram.com/p/DSS62jAkhpC/',
      embedUrl: 'https://www.instagram.com/p/DSS62jAkhpC/embed/',
    },
    {
      id: '02',
      title: 'At the mechanic',
      handle: '@clips_colosseum',
      analysis: 'A comedy clip set inside an auto shop.',
      image: '/culture-comedy-mechanic.png',
      imageAlt: 'Two mechanics working beside a vehicle on a lift',
      url: 'https://www.instagram.com/p/DZMfvnCg4AK/',
      embedUrl: 'https://www.instagram.com/p/DZMfvnCg4AK/embed/',
    },
    {
      id: '03',
      title: 'Comedy 03',
      handle: '@petercainedogtraining',
      analysis: 'The third selection in the Comedy collection.',
      url: 'https://www.instagram.com/p/DYp_KLdJpcz/',
      embedUrl: 'https://www.instagram.com/p/DYp_KLdJpcz/embed/',
    },
    {
      id: '04',
      title: 'Comedy 04',
      handle: '@5nightattrump',
      analysis: 'The fourth selection in the Comedy collection.',
      url: 'https://www.instagram.com/p/DchtgijtJrB/',
      embedUrl: 'https://www.instagram.com/p/DchtgijtJrB/embed/',
    },
  ],
  'new-age-athletes': [
    instagramPost('05', 'Db6GcxTTN1V', 'Super grip strength athlete', 'Super grip strength athlete, the likes we have not seen in a long time.'),
    instagramPost('06', 'DcUqAfmhYfc', 'Another super grip strength athlete', 'Another super grip strength athlete.'),
    instagramPost('04', 'DctHzV1zRCX', 'New Age Athletes 04'),
    instagramPost('03', 'Da8fm2SOtLG', 'New Age Athletes 03'),
    {
      id: '01',
      title: 'NYX',
      handle: '@nyx_vostok',
      analysis: "Me. Founder of the site. First facial athlete. There are looksmaxxers, there are facial yoga people but then there's me, who tries to focus on the whole compass of improving your face, across the board.",
      url: 'https://www.instagram.com/p/Dcd2UceA3Sy/',
      embedUrl: 'https://www.instagram.com/p/Dcd2UceA3Sy/embed/',
    },
    {
      id: '02',
      title: 'Modern-Day Spider-Man',
      handle: '@swholeanimal',
      analysis: 'Modern day spiderman, focusing on creating grooves in his fingers to hang onto stuff, and run faster.',
      url: 'https://www.instagram.com/p/DZLwgMRMgmJ/',
      embedUrl: 'https://www.instagram.com/p/DZLwgMRMgmJ/embed/',
    },
  ],
  art: [
    {
      id: '01',
      title: 'Art 01',
      handle: '@the.culture.guy',
      analysis: 'The first selection in the Art collection.',
      url: 'https://www.instagram.com/p/DZ1ep8egbJN/?img_index=1',
      embedUrl: 'https://www.instagram.com/p/DZ1ep8egbJN/embed/',
    },
  ],
  history: [
    {
      id: '01',
      title: 'History 01',
      handle: '@hidden.ny',
      analysis: 'The first selection in the History collection.',
      url: 'https://www.instagram.com/p/DZ75125kZ2T/?img_index=1',
      embedUrl: 'https://www.instagram.com/p/DZ75125kZ2T/embed/',
    },
    {
      id: '02',
      title: 'History 02',
      handle: '@historycoolkids',
      analysis: 'The second selection in the History collection.',
      url: 'https://www.instagram.com/p/DZsnBp8iGTI/',
      embedUrl: 'https://www.instagram.com/p/DZsnBp8iGTI/embed/',
    },
    {
      id: '03',
      title: 'History 03',
      handle: '@historyfeelsthepodcast',
      analysis: 'The third selection in the History collection.',
      url: 'https://www.instagram.com/p/DcgxEsITHYE/',
      embedUrl: 'https://www.instagram.com/p/DcgxEsITHYE/embed/',
    },
  ],
  fights: [
    {
      id: '01',
      title: 'Fights 01',
      handle: '@amanjaat_no1',
      analysis: 'The first selection in the Fights collection.',
      url: 'https://www.instagram.com/p/DapPIr_OsPG/',
      embedUrl: 'https://www.instagram.com/p/DapPIr_OsPG/embed/',
    },
    instagramPost('02', 'Daovn_YsncU', 'Fights 02'),
  ],
  religion: [
    instagramPost('02', 'DcWRjpYRqkh', 'Religion 02'),
    instagramPost('03', 'DVchagfjba7', 'Religion 03'),
    {
      id: '01',
      title: 'Religion 01',
      videoSrc: '/instagram-videos/DcXagl7y_Ce.mp4',
      handle: '@mindempirex_',
      analysis: 'The first selection in the Religion collection.',
      url: 'https://www.instagram.com/p/DcXagl7y_Ce/',
      embedUrl: 'https://www.instagram.com/p/DcXagl7y_Ce/embed/',
    },
  ],
}
