export const cultureFeatures = {
  music: [
    {
      id: '01',
      title: 'pr0crastn8',
      handle: '@pr0crastn8',
      analysis: 'New artist, still figuring out his sound 6/10, intersting.',
      image: '/culture-music-pr0crastn8.png',
      imageAlt: 'A musician framed by an electric-blue circular mirror',
      url: 'https://www.instagram.com/p/DYL5FOKzq7Q/',
      embedUrl: 'https://www.instagram.com/p/DYL5FOKzq7Q/embed/',
    },
    {
      id: '02',
      title: 'iam24th',
      handle: '@iam24th',
      analysis: 'New music find: “yeah huh and i get it.”',
      image: '/culture-music-iam24th.png',
      imageAlt: 'A hooded musician standing beside the ocean',
      url: 'https://www.instagram.com/p/DWkLVRzx_sm/',
      embedUrl: 'https://www.instagram.com/p/DWkLVRzx_sm/embed/',
    },
    {
      id: '03',
      title: 'corpo.corpo.corpo',
      handle: '@corpo.corpo.corpo',
      analysis: 'A new atmospheric music selection.',
      image: '/culture-music-corpo.png',
      imageAlt: 'A pale, glitched music-video frame in a wooded landscape',
      url: 'https://www.instagram.com/p/DZWPUnTAN86/',
      embedUrl: 'https://www.instagram.com/p/DZWPUnTAN86/embed/',
      additionalLinks: [
        {
          label: 'Second music post',
          url: 'https://www.instagram.com/p/DYIetfiyx4f/',
        },
      ],
    },
  ],
  memes: [
    {
      id: '01',
      title: 'Me in the car',
      handle: '@unemployed.clipper',
      analysis: 'Mechanic: How did you not hear the noise your car was making?',
      image: '/culture-meme-mechanic.png',
      imageAlt: 'A man vibing in a car beneath a mechanic joke',
      url: 'https://www.instagram.com/p/DYkj1BHJkkr/',
      embedUrl: 'https://www.instagram.com/p/DYkj1BHJkkr/embed/',
    },
    {
      id: '02',
      title: 'Average Instagram user',
      handle: '@offbeatoffender',
      image: '/culture-meme-instagram-user.png',
      imageAlt: 'Average Instagram user meme over an illustrated photo album',
      url: 'https://www.instagram.com/p/DTNor-fkgxO/',
      embedUrl: 'https://www.instagram.com/p/DTNor-fkgxO/embed/',
    },
    {
      id: '03',
      title: 'My favorite word',
      handle: '@clips',
      analysis: 'Me at 80 years old with dementia trying to remember my favorite word.',
      image: '/culture-meme-favorite-word.png',
      imageAlt: 'A nighttime movie scene beneath a joke about remembering a favorite word',
      url: 'https://www.instagram.com/p/DT90Nv0Etb_/',
      embedUrl: 'https://www.instagram.com/p/DT90Nv0Etb_/embed/',
    },
  ],
  comedy: [
    {
      id: '01',
      title: 'Railroad crossing',
      handle: '@slimerboy9000',
      analysis: 'A quick drive-by comedy clip.',
      image: '/culture-comedy-railroad.png',
      imageAlt: 'A driver waiting behind a car at a railroad crossing',
      url: 'https://www.instagram.com/p/DSS62jAkhpC/',
      embedUrl: 'https://www.instagram.com/p/DSS62jAkhpC/embed/',
    },
    {
      id: '02',
      title: 'At the mechanic',
      handle: '@clips_colosseum',
      analysis: 'A comedy clip set inside an auto shop.',
      image: '/culture-comedy-mechanic.png',
      imageAlt: 'Two mechanics working beside a vehicle on a lift',
      url: 'https://www.instagram.com/p/DZMfvnCg4AK/',
      embedUrl: 'https://www.instagram.com/p/DZMfvnCg4AK/embed/',
    },
    {
      id: '03',
      title: 'Comedy 03',
      handle: '@petercainedogtraining',
      analysis: 'The third selection in the Comedy collection.',
      url: 'https://www.instagram.com/p/DYp_KLdJpcz/',
      embedUrl: 'https://www.instagram.com/p/DYp_KLdJpcz/embed/',
    },
    {
      id: '04',
      title: 'Comedy 04',
      handle: '@5nightattrump',
      analysis: 'The fourth selection in the Comedy collection.',
      url: 'https://www.instagram.com/p/DchtgijtJrB/',
      embedUrl: 'https://www.instagram.com/p/DchtgijtJrB/embed/',
    },
  ],
  'new-age-athletes': [
    {
      id: '01',
      title: 'NYX',
      handle: '@nyx_vostok',
      analysis: "Me. Founder of the site. First facial athlete. There are looksmaxxers, there are facial yoga people but then there's me, who tries to focus on the whole compass of improving your face, across the board.",
      url: 'https://www.instagram.com/p/Dcd2UceA3Sy/',
      embedUrl: 'https://www.instagram.com/p/Dcd2UceA3Sy/embed/',
    },
    {
      id: '02',
      title: 'Modern-Day Spider-Man',
      handle: '@swholeanimal',
      analysis: 'Modern day spiderman, focusing on creating grooves in his fingers to hang onto stuff, and run faster.',
      url: 'https://www.instagram.com/p/DZLwgMRMgmJ/',
      embedUrl: 'https://www.instagram.com/p/DZLwgMRMgmJ/embed/',
    },
  ],
  art: [
    {
      id: '01',
      title: 'Art 01',
      handle: '@the.culture.guy',
      analysis: 'The first selection in the Art collection.',
      url: 'https://www.instagram.com/p/DZ1ep8egbJN/?img_index=1',
      embedUrl: 'https://www.instagram.com/p/DZ1ep8egbJN/embed/',
    },
    {
      id: '02',
      title: 'Art 02',
      handle: '@maxvoao',
      analysis: 'The second selection in the Art collection.',
      url: 'https://www.instagram.com/p/Db03EO5CJi-/?img_index=4',
      embedUrl: 'https://www.instagram.com/p/Db03EO5CJi-/embed/',
    },
  ],
  history: [
    {
      id: '01',
      title: 'History 01',
      handle: '@hidden.ny',
      analysis: 'The first selection in the History collection.',
      url: 'https://www.instagram.com/p/DZ75125kZ2T/?img_index=1',
      embedUrl: 'https://www.instagram.com/p/DZ75125kZ2T/embed/',
    },
    {
      id: '02',
      title: 'History 02',
      handle: '@historycoolkids',
      analysis: 'The second selection in the History collection.',
      url: 'https://www.instagram.com/p/DZsnBp8iGTI/',
      embedUrl: 'https://www.instagram.com/p/DZsnBp8iGTI/embed/',
    },
    {
      id: '03',
      title: 'History 03',
      handle: '@historyfeelsthepodcast',
      analysis: 'The third selection in the History collection.',
      url: 'https://www.instagram.com/p/DcgxEsITHYE/',
      embedUrl: 'https://www.instagram.com/p/DcgxEsITHYE/embed/',
    },
  ],
  fights: [
    {
      id: '01',
      title: 'Fights 01',
      handle: '@amanjaat_no1',
      analysis: 'The first selection in the Fights collection.',
      url: 'https://www.instagram.com/p/DapPIr_OsPG/',
      embedUrl: 'https://www.instagram.com/p/DapPIr_OsPG/embed/',
    },
    {
      id: '02',
      title: 'Fights 02',
      handle: 'Instagram',
      analysis: 'The second selection in the Fights collection.',
      url: 'https://www.instagram.com/p/DcgC41ahMuY/',
      embedUrl: 'https://www.instagram.com/p/DcgC41ahMuY/embed/',
    },
  ],
  religion: [
    {
      id: '01',
      title: 'Religion 01',
      handle: '@mindempirex_',
      analysis: 'The first selection in the Religion collection.',
      url: 'https://www.instagram.com/p/DcXagl7y_Ce/',
      embedUrl: 'https://www.instagram.com/p/DcXagl7y_Ce/embed/',
    },
  ],
}
