// Public source links selected for Academy. Captions are editorial descriptions,
// not independent verification of claims made by the original creators.
const selections = [
  ['Dc1jPRAJ6OV', 'culture/comedy', 'Women in politics', 'A stand-up comedy excerpt.'],
  ['Dc6UUkvAchy', 'culture/video-games/extra', 'Elder Scrolls meets Vietnam', 'An AI-generated gaming parody.'],
  ['DbXYccCK5li', 'culture/contemplative', 'Past and present selves', 'A reflection on attention and identity.'],
  ['DbdiErUNJzE', 'culture/new-age-athletes', 'Hybrid athletic training', 'Strength, running, and martial arts in one training practice.'],
  ['Da_lQpXvezw', 'culture/contemplative', 'Jung, symbols, and archetypes', 'A creator explores symbolic approaches to understanding the mind.'],
  ['DbRgavnvayh', 'culture/comedy', 'Surveillance everywhere', 'A satirical skit filled with cameras and a Palantir-branded tablet.'],
  ['Db_gyy6HOUB', 'science/looksmaxxing', 'A practitioner discusses fillers', 'An aesthetic practitioner presents their perspective on cosmetic results.'],
  ['DcG3myHkSaB', 'culture/video-games', 'One fish, thousands of hours', 'Dexerto shares a World of Warcraft fishing story.'],
  ['Db7FuUHiQqi', 'culture/contemplative', 'Learning through practice', 'A post discussing learning by doing through an Aristotle quotation.'],
  ['Dbt89BggZd9', 'culture/art', 'Jim Carrey paints', 'A look at the actor’s painting practice.'],
  ['Db_zMbgGXcI', 'culture/memes', 'Another layer of the matrix', 'An escape-the-matrix joke.'],
  ['Db8n2OdOIWm', 'culture/contemplative', 'Robert Anton Wilson on perception', 'An excerpt about subjective experience and mysticism.'],
  ['Db_HibiAU8t', 'culture/art/extra', 'Legend of Trump', 'An AI gaming parody.'],
  ['DbpHMpdS5ma', 'business', 'Tobi Lütke on public speaking', 'An anecdote about confidence and preparing to speak.'],
  ['DbnqoiqgkXJ', 'culture/religion/occult', 'Currency of spirits', 'A creator introduces a book about witchcraft.'],
  ['DbBT2gvObIb', 'culture/religion/occult', 'Alchemical symbolism', 'An interpretation of alchemy as inner transformation.'],
  ['DbL8q6gAHKI', 'culture/contemplative', 'A fourfold view of reality', 'Pravir Malik presents a speculative philosophical framework.'],
  ['DZV7Nd-NHmX', 'culture/religion/occult', 'Elemental shadow work', 'A spiritual practice presented through the work of Franz Bardon.'],
  ['DbLEjUoGKV_', 'culture/religion/occult', 'Archons and consciousness', 'A creator discusses an esoteric belief about consciousness.'],
  ['DbOyLSIAmf8', 'culture/history', 'Remembering Robert Ritner', 'An Egyptology post connecting scholarship and ancient Egyptian magic.'],
  ['DaKXnZtKJeu', 'culture/history', 'The infrastructure of Rome', 'A historical overview of Roman engineering.'],
  ['DZwpXaIMhy0', 'culture/religion', 'Understanding Kabbalah', 'A discussion of the religious tradition and misconceptions surrounding it.'],
  ['Db7tJrIQsT9', 'business', 'Reading Zero to One', 'A creator recommends Peter Thiel’s entrepreneurship book.'],
  ['Db53IClBkhM', 'culture/religion/occult', 'The History of Magic', 'An introduction to an audiobook about Hermetic traditions.'],
  ['DbybKu0vnDX', 'culture/contemplative', 'Consciousness before life?', 'A speculative discussion about the origins of consciousness.'],
  ['DbydVjzByKz', 'culture/history', 'The Bronze Age collapse', 'A short introduction to the end of several Bronze Age societies.'],
  ['DWeZrlYjigw', 'culture/religion/occult', 'Damien Echols on ceremonial magic', 'A conversation excerpt from The Midnight Gospel.'],
  ['DbmMdRQjDUp', 'science/looksmaxxing', 'Fascia and facial aesthetics', 'A creator promotes a facial-taping approach; its efficacy is not established here.'],
  ['DYYgHmphqba', 'culture/new-age-athletes', 'A gainer backflip', 'An athletic acrobatics clip.'],
  ['Dbl9yTtJE1H', 'culture/film', 'Gary Cooper in Children of Divorce', 'A silent-film excerpt from the 1927 production.'],
  ['DbvKpRHxwrw', 'science/workout', 'Gymnastics hip mobility', 'A gymnastics mobility demonstration.'],
  ['DbnesgHRSAx', 'culture/street/vagabond', 'Life on a shantyboat', 'A glimpse of an off-grid river lifestyle.'],
  ['DbY0-Vszong', 'science/looksmaxxing', 'Posture and appearance', 'A creator’s perspective on posture and aesthetics.'],
  ['DYjHM4LhnFc', 'science/workout', 'Yoga forward fold', 'A flexibility demonstration.'],
  ['DY-WG0qzAhJ', 'culture/new-age-athletes', 'Anime-inspired grip training', 'A themed grip-strength routine.'],
  ['DaeROPNOG68', 'culture/new-age-athletes', 'Hands and forearms', 'A creator demonstrates progressive grip training.'],
  ['Dawk_jgHEFC', 'culture/religion/occult', 'Manly P. Hall on magic', 'A quotation exploring an esoteric view of matter.'],
  ['DbfSjiYDiFG', 'culture/contemplative', 'Nietzsche and self-mastery', 'A philosophical quotation shared for reflection.'],
  ['Dbbw_6kS5Hd', 'culture/art/extra', 'Anakin’s alternate family', 'A Midjourney-generated Star Wars reimagining.'],
  ['DbCp8_nNoA0', 'culture/memes', 'Appearances and character', 'A meme about edgy personalities and public virtue.'],
  ['DZv619Sp8Qp', 'conspiracy', 'Michael Talbot and the holographic universe', 'An interview excerpt with speculative commentary from the posting account.'],
  ['DbRaYbXkSfr', 'science/astrology', 'Saturn, time, and responsibility', 'An astrological interpretation.'],
  ['DbLMz1yDClg', 'culture/contemplative', 'Thomas Campbell on spiritual choices', 'A post presenting a metaphysical perspective.'],
  ['DbNdSlmS700', 'culture/music', 'California Girls reaction', 'A music reaction featuring Future.'],
  ['DbM-aLyvaLf', 'science/physics', 'Imagining four dimensions', 'A visual explanation of higher-dimensional space.'],
  ['Da8ImNtRnAV', 'science/physics', 'Ulexite and optical illusions', 'A post exploring optical effects and Pepper’s ghost.'],
  ['DbGWyNGuZSM', 'business', 'Recurring-revenue business ideas', 'A creator’s list of ordinary service businesses.'],
  ['DbFVzDHm3Cx', 'culture/religion/occult', 'Leadbeater’s astral plane', 'A quotation from an esoteric text.'],
  ['DadoXOymiWM', 'crime', 'A Naples arrest story', 'A creator discusses reported criminal charges; the account’s claims are not independently verified here.'],
  ['DYuVa5hgi__', 'culture/contemplative', 'Nietzsche and mysticism', 'An interview excerpt about philosophy and spiritual experience.'],
  ['DYnvziuO4ya', 'culture/religion/occult', 'In Sorcery’s Shadow', 'A post introducing a book about anthropology and sorcery.'],
  ['DYZvCm9E8E4', 'conspiracy', 'Claims about psychic espionage', 'An interview discussing alleged intelligence experiments.'],
  ['DXp1U4kiYo2', 'culture/religion', 'Geometry and Hindu symbolism', 'A speculative comparison between biological forms and sacred geometry.'],
  ['Da3l6lwP2kp', 'conspiracy', 'A haunted-woods story', 'A paranormal account presented by its creator.'],
  ['Dapy8D4jTAb', 'freedom', 'Pokémon Go and location data', 'A creator raises questions about location data and military technology; the claimed connection is not verified here.'],
  ['DavuH1mkdyq', 'culture/religion', 'Anakin and Lucifer', 'A symbolic interpretation of the Star Wars character.'],
  ['Da0ogNYgPbG', 'culture/memes', 'Batman questions the Joker', 'A comic take on the interrogation scene.'],
  ['Da38WIPyn2F', 'culture/religion/occult', 'The Lesser Key of Solomon', 'A paranormal creator discusses an occult text and a ghost-box session.'],
  ['DYgCHotNVVv', 'freedom', 'Eyewear and facial recognition', 'A product promotion claiming to interfere with recognition systems; performance is not verified here.'],
  ['DZf7g2tzIYb', 'career/tech', 'BoxPhone hardware', 'A look at hardware for controlling multiple mobile devices.'],
  ['DYSd0lkyae8', 'career/tech', 'Building a personal site with Neocities', 'A creator explores the Frutiger Aero aesthetic and personal websites.'],
  ['DanrbjZyqpu', 'culture/music', 'Higher by boy2000', 'Music paired with a rainy city scene.'],
  ['DayOpsAvDjs', 'culture/art', 'Kunichika’s kabuki print', 'A post about Onoe Kikugorō in the supernatural role of Tenjiku Tokubē.'],
  ['Da5Ko1vMiPH', 'culture/history', 'Berlin around 1900', 'A historical overview of the growing German capital.'],
  ['DayD7_3PwOb', 'culture/art/extra', 'Geeked cartoons', 'A stylized AI cartoon parody.'],
  ['DatRUAXzdxF', 'culture/video-games/extra', 'Geeked inside Skyrim', 'A Skyrim-themed gaming meme.'],
  ['DWKnjrME-Aq', 'culture/religion', 'Responsibility across generations', 'A sermon excerpt about giving and supporting younger people.'],
  ['DZ-lj1vjQT4', 'culture/comedy', 'A generational rant', 'A comedy clip about entitlement.'],
  ['DaW6EH9M6gD', 'conspiracy', 'Dolores Cannon and future timelines', 'A post discussing speculative accounts from hypnosis sessions.'],
  ['DabxLC1I69S', 'conspiracy', 'Claims about directed sound', 'A creator discusses alleged psychological-operation technologies; the claims are not verified here.'],
  ['DajLD1BMNjs', 'culture/religion', 'Mauro Biglino’s interpretations', 'A discussion of controversial readings of ancient religious texts.'],
  ['DamTQIzs-Ks', 'conspiracy', 'Alex Collier’s extraterrestrial account', 'An unverified account of a supposed extraterrestrial hierarchy.'],
  ['Daq5mgWkllJ', 'business', 'The proposed Akon City', 'A post revisiting a proposed megacity development in Senegal.'],
  ['DaqOPe5OKZX', 'science/animals', 'Dachshund life', 'A humorous dog clip.'],
  ['Dan5IkuhsNP', 'science/animals', 'Respecting alligators', 'An animal handler explains why alligators should not be treated as pets.'],
  ['Dao7Iv4PxPd', 'science/animals/insects', 'Spider and bombardier beetle', 'A macro wildlife encounter.'],
  ['DaZ4eroDCYJ', 'culture/contemplative', 'Preparing to live', 'A reflection on delaying action.'],
  ['DaDVQ6Qu0eN', 'culture/comedy', 'A Kool-Aid satire', 'A creator’s satirical sketch.'],
  ['DaqCOScxp31', 'culture/street', 'A Saint Louis neighborhood vlog', 'A local street-culture video excerpt.'],
  ['Dailf_XsGhs', 'science/physics', 'The Hercules–Corona Borealis Great Wall', 'A popular-science post about a proposed large cosmic structure.'],
  ['DaYTxxdRdmB', 'science/workout', 'Split-squat speed work', 'An athletic training demonstration.'],
  ["Db9myCmRszu", "culture/comedy", "Kids and dramatic reactions", "YPK Raye acts out a childhood mishap."],
  ["Db3l5RqK9rh", "culture/video-games/extra", "Khajiit fan comedy", "An AI-generated Skyrim parody."],
  ["DcB9aeuo16-", "culture/religion/occult", "The Sons of God", "A bookshop presents R. Swinburne Clymer’s mystical text."],
  ["Db5-q3XiB7F", "culture/history", "Divination through Virgil", "A rare-book seller discusses the tradition of consulting Virgil at random."],
  ["Db0bu1GgALJ", "culture/video-games", "Alliance characters: then and now", "A comparison of World of Warcraft character models."],
  ["Da8RUT-FlXS", "culture/religion/occult", "Alex Sanders and Alexandrian Wicca", "A photographic post about a figure in the modern occult revival."],
  ["DbS7ty6pn4z", "career/modeling", "Presentation and first impressions", "A speaker discusses how clothing and presentation affect perception."],
  ["DYnSBwosWP4", "culture/video-games/other-games", "A spacecraft in EVE Online", "A space-game clip featuring the Astero."],
  ["DbWeNwrz0NS", "conspiracy", "The supposedly banned glasses", "A viral claim about eyewear, accompanied by an Instagram community note disputing the ban."],
  ["DUgLWjCCRjA", "culture/street", "A Chicago street exchange", "Footage of a verbal exchange between police and people on the street."],
  ["Daog7SVmN5r", "culture/contemplative", "Hesiod on procrastination", "A quotation about diligence and putting things off."],
  ["DYCmPlatYcV", "culture/new-age-athletes", "Cheststand practice", "An acrobatic flexibility demonstration."],
  ["DaIQqqux42o", "culture/street", "Saint Louis street life", "A neighborhood-vlog excerpt."],
  ["DaQ6vndK7tQ", "culture/memes", "Wrestling witchcraft", "A wrestling meme."],
  ["DansDT1qXHR", "culture/contemplative", "Imagining brain mapping", "A philosophical post about understanding the mind."],
  ["DankeIHlOzw", "culture/art", "Beauty standards in medieval portraits", "An art-history post examining portrait conventions."],
  ["DamDqkrH0xb", "culture/contemplative", "Making one’s way in the world", "A philosophical quotation about wisdom and social life."],
  ["DaGAfiRIVi4", "culture/art", "Motel Mario", "A Super Mario-inspired 3D animation."],
  ["DagaNyYTSM_", "culture/art/extra", "Looney Tunes dating-show parody", "An AI cartoon reimagining of a dating-show format."],
  ["Dal4mbEschC", "culture/video-games/other-games", "America Souls", "A parody of an Elden Ring opening cinematic."],
  ["DadhUAmsnFm", "culture/religion", "Remembering who you are", "A reflection using Hindu and Krishna imagery."],
  ["DaQdAivKQ2V", "career/tech", "An open-source intelligence directory", "A creator introduces a collection of public research tools."],
  ["DadY6RKIejq", "culture/contemplative", "Donald Hoffman on perception", "An introduction to Hoffman’s theory of perception as an interface."],
  ["DYzw3QrDD4_", "career/socialMedia", "A creator-led advertising system", "An agency describes its approach to short-form advertising."],
  ["DaY5hGZDU9x", "culture/religion/occult", "The alchemist’s journey", "A quotation about an esoteric conception of existence."],
  ["DZps61HsUx7", "career/socialMedia", "Scaling creator content", "An agency presents a short-form content strategy."],
  ["DOwJHc5AIIh", "culture/contemplative", "Breaking the daily cycle", "A motivational reflection on routine."],
  ["DaBUQq_sZf3", "career/modeling", "V at Vogue World", "A fashion-event appearance."],
  ["DZaDY44pVy8", "culture/contemplative", "Persistence, according to Daffy Duck", "A creator reflects on perseverance through an animated character."],
  ["DX5MP5kqcPJ", "culture/contemplative", "Introducing Seneca", "A short overview of the Stoic philosopher."],
  ["DUyguugD2V4", "culture/memes", "Internet nostalgia: 2016", "A retrospective meme about online culture."],
]

export const reviewedInstagram = selections.map(([post, collection, title, caption]) => ({
  id: `reviewed-${post}`, post, collection, title, caption,
  url: `https://www.instagram.com/p/${post}/`,
  embedUrl: `https://www.instagram.com/p/${post}/embed/`,
}))

export const instagramSelections = (collection) => reviewedInstagram.filter((feature) => feature.collection === collection)
